export const ORDER_STATUSES = {
  NEW: 'NEW',
  IN_PREPARATION: 'IN_PREPARATION',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  ACCEPTED: 'ACCEPTED',
  PICKED_UP: 'PICKED_UP',
  COMPLETED: 'COMPLETED',
};
